name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - ros2
  pull_request:
    branches:
      - ros2

jobs:
  industrial_ci:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy, rolling]
        ROS_REPO: [testing, main]
    env:
      ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Source tests
        uses: "ros-industrial/industrial_ci@master"
        env:
          UPSTREAM_WORKSPACE: "github:LeoRover/leo_common-ros2#${{ matrix.ROS_DISTRO }}"
          PYLINT_CHECK: true
          PYLINT_ARGS: "--rcfile=src/leo_robot-ros2/.pylintrc"
